<!DOCTYPE html>
<html lang="zh-CN">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="keywords" content="">
		<title>众智联云科技(山东)有限公司</title>
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/hwslider.css" rel="stylesheet">
		<link href="/css/fonts.css" rel="stylesheet">
		<link href="/css/reset.css" rel="stylesheet">
		<link href="/css/style.css" rel="stylesheet">
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
      <script src="/js/html5shiv.min.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
	</head>

	<body style="overflow-x:hidden;">
		<#include "./icn/header.ftlh">
		<!--大图-->
		<section class="ban">
			<img src="/images/b2.jpg">
		</section>
		<section class="ser-dan ser-danx">

			<div class="container">
				<div class="pic-tit">
					<div class="ab-tit">
						<h2><em class="f-normal">案例</em><em>|</em><em class="f-normal">展示</em></h2>
						<p class="s-font">自动化工业生产项目案例</p>
					</div>
					<div class="v-line"></div>
					
				</div>
			<!-- 项目导航 -->	
				<div class="row tab">
					<ul>
						<li>
							<a href="javascript:void(0);">生产配件</a>
						</li>
						<li>
							<a href="javascript:void(0);">电工电气</a>
						</li>
						<li>
							<a href="javascript:void(0);">机械机电</a>
						</li>
						<li>
							<a href="javascript:void(0);">分拣输送</a>
						</li>
						<li>
							<a href="javascript:void(0);">环境检测</a>
						</li>
						<li>
							<a href="javascript:void(0);">成分检测</a>
						</li>
					</ul>
					<div style="clear: both;"></div>
				</div>
			<!-- 服务类型页面内容 -->
			
			</div>
		</section>
	<!-- 标题一内容 -->
		<div class="ta-list tab0 show fw" style="overflow-x:hidden;">
			<section class="new-dan">
				<div class="container auto">
					<div class="clearfix">
						<div class="newdan-r">
				<!-- ----页面内容------- -->			
							<div class="clearfix">
								<figure class="col-xs-6 col-sm-6 col-md-3">
									<img src="images/g1-1.png">
									<figcaption>车轮轴生产</figcaption>
								</figure>
								<figure class="col-xs-6 col-sm-6 col-md-3">
									<img src="images/g1-2.png">
									<figcaption>配件生产线</figcaption>
								</figure>
								<figure class="col-xs-6 col-sm-6 col-md-3">
									<img src="images/g1-3.png">
									<figcaption>配件生产</figcaption>
								</figure>
								<figure class="col-xs-6 col-sm-6 col-md-3">
									<img src="images/g1-4.png">
									<figcaption>配件生产</figcaption>
								</figure>
							</div>
							
							<div class="page tc clearfix">
								<a href="javascript:void(0);" class="prev"><em></em>上一页</a>
								<span>1</span>
								<a href="javascript:void(1)">2</a>...
								<a href="javascript:void(0);">10</a>
								<a href="javascript:void(0);" class="next">下一页<em></em></a>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
		<!-- <div class="container"> -->
		<!-- 标题二内容 -->
			<div class="ta-list tab1 fw" >
				<section class="new-dan">
					<div class="container auto">
						<div class="clearfix">
							<div class="newdan-r">
				<!-- ----页面内容----- -->			
								<div class="clearfix">
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2-1.png">
										<figcaption>电工电气类</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2-2.png">
										<figcaption>电工电气类</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2-1.png">
										<figcaption>电工电气类</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2-2.png">
										<figcaption>电工电气类</figcaption>
									</figure>
								</div>
								
								<div class="page tc clearfix">
									<a href="javascript:void(0);" class="prev"><em></em>上一页</a>
									<span>1</span>
									<a href="javascript:void(1)">2</a>...
									<a href="javascript:void(0);">10</a>
									<a href="javascript:void(0);" class="next">下一页<em></em></a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		<!-- 标题三 内容-->	
			<div class="ta-list tab2 clearfix fw" style="overflow-x:hidden;">
				<section class="new-dan">
					<div class="container auto">
						<div class="clearfix">
							<div class="newdan-r">
				<!-- ------页面内容------ -->		
								<div class="clearfix">
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g4.png">
										<figcaption>机械配件</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g4-1.png">
										<figcaption>机械生产线</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g4.png">
										<figcaption>机械配件</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g4-1.png">
										<figcaption>机械生产线</figcaption>
									</figure>
								</div>
								
								<div class="page tc clearfix">
									<a href="javascript:void(0);" class="prev"><em></em>上一页</a>
									<span>1</span>
									<a href="javascript:void(1)">2</a>...
									<a href="javascript:void(0);">10</a>
									<a href="javascript:void(0);" class="next">下一页<em></em></a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
			
		<!-- 标题四内容 -->	
			<div class="ta-list tab3" style="overflow-x:hidden;">
				<!-- <div class="wi"><img src="images/peixun_01.jpg"></div>
				<div class="wi"><img src="images/peixun_02.jpg"></div>
				<div class="wi"><img src="images/peixun_03.jpg"></div> -->
				<section class="new-dan">
					<div class="container auto">
						<div class="clearfix">
							<div class="newdan-r">
						<!-- -----页面内容----- -->
								<div class="clearfix">
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5.png">
										<figcaption>陶瓷生产线传输</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5.png">
										<figcaption>陶瓷生产线传输</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5.png">
										<figcaption>陶瓷生产线传输</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5.png">
										<figcaption>陶瓷生产线传输</figcaption>
									</figure>
								</div>
								
								
								<div class="page tc clearfix">
									<a href="javascript:void(0);" class="prev"><em></em>上一页</a>
									<span>1</span>
									<a href="javascript:void(1)">2</a>...
									<a href="javascript:void(0);">10</a>
									<a href="javascript:void(0);" class="next">下一页<em></em></a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		<!-- 标题五内容 -->
			<div class="ta-list tab4 fw" style="overflow-x:hidden;">
				<section class="new-dan">
					<div class="container auto">
						<div class="clearfix">
							<div class="newdan-r">
				<!-- -----页面内容----- -->		
								<div class="clearfix">
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5-1.png">
										<figcaption>大气污染监测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5-2.png">
										<figcaption>环境监测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5-1.png">
										<figcaption>大气污染监测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g5-2.png">
										<figcaption>环境监测</figcaption>
									</figure>
								</div>
								
								<div class="page tc clearfix">
									<a href="javascript:void(0);" class="prev"><em></em>上一页</a>
									<span>1</span>
									<a href="javascript:void(1)">2</a>...
									<a href="javascript:void(0);">10</a>
									<a href="javascript:void(0);" class="next">下一页<em></em></a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		<!-- 页面6内容 -->
			<div class="ta-list tab5 fw" style="overflow:none;">
				<section class="new-dan">
					<div class="container auto">
						<div class="clearfix">
							<div class="newdan-r">
					<!-- -----页面内容----- -->		
								<div class="clearfix">
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
								</div>
								<div class="clearfix">
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
									<figure class="col-xs-6 col-sm-6 col-md-3">
										<img src="images/g2.png">
										<figcaption>空调外机检测</figcaption>
									</figure>
								</div>
								
								
								
								<div class="page tc clearfix">
									<a href="javascript:void(0);" class="prev"><em></em>上一页</a>
									<span>1</span>
									<a href="javascript:void(1)">2</a>...
									<a href="javascript:void(10);">10</a>
									<a href="javascript:void(0);" class="next">下一页<em></em></a>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
			
		
<!--页脚-->
		<#include "./icn/footer.ftlh">
		<script src="js/jquery.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.hwslider.min.js"></script>
		<script src="js/main.js"></script>
		<script>
			/*banner*/
			$(function() {
				$("#hwslider").hwSlider({
					height: 190,
					autoPlay: true,
					arrShow: true,
					dotShow: true,
					touch: true
				});
			});
		</script>
	</body>

</html>